[platformio]
    libdeps_dir = .pio/shared_libdeps
    ; core_dir = C:/pio

[env]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

platform_packages =
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32.git

lib_ldf_mode = deep+

build_flags =
    -O3
    -Wno-pragmas
    -DLED_BUILTIN=2
    -DIR_PIN=13
    -DCORE_DEBUG_LEVEL=0
    -I include/defs
    -I include/hardware
    -I include/modes
    -I include/profiles
    -I include/services
    -I include/hardware/sensors
    -I include/strategies

lib_deps =
    z3t0/IRremote
    fastled/FastLED
    madhephaestus/ESP32Servo
    mathieucarbou/ESPAsyncWebServer
    DNSServer
    Preferences
    pololu/VL53L0X

[env:caipora]
build_flags = 
    ${env.build_flags}
    -DROBOT_CAIPORA

[env:smoker]
build_flags = 
    ${env.build_flags}
    -DROBOT_SMOKER

[env:smokerauto]
build_flags = 
    ${env.build_flags}
    -DROBOT_SMOKERAUTO

[env:arruela]
build_flags = 
    ${env.build_flags}
    -DROBOT_ARRUELA

[env:marola]
build_flags =
    ${env.build_flags}
    -DROBOT_MAROLA

[env:fuego]
build_flags =
    ${env.build_flags}
    -DROBOT_FUEGO

[env:fueguito]
build_flags =
    ${env.build_flags}
    -DROBOT_FUEGUITO

[env:briga]
build_flags =
    ${env.build_flags}
    -DROBOT_BRIGA